//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDeVehiculo
    {
        public BaseDeVehiculo()
        {
            this.ElManifiestoDeCargas = new HashSet<ElManifiestoDeCarga>();
            this.ProgramacionParaSeguimientoes = new HashSet<ProgramacionParaSeguimiento>();
            this.LaRotacionRemolques = new HashSet<LaRotacionRemolque>();
        }
    
        public string CodigoDeVehiculo { get; set; }
        public string NitEmpresa { get; set; }
        public string Placa { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoDeMarca { get; set; }
        public string CodigoTipoDeVehiculo { get; set; }
        public string CodigoTipoCombustible { get; set; }
        public string CodigoDeColor { get; set; }
        public string CodigoDeCarroceria { get; set; }
        public string CodigoTipoDeMotor { get; set; }
        public string CodigoUbicacion { get; set; }
        public string CodigoDiferencial { get; set; }
        public string CodigoTipoDeTransmision { get; set; }
        public string NumeroDeChasis { get; set; }
        public Nullable<int> NumeroDePuertas { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public Nullable<System.DateTime> FechaDeAdquisision { get; set; }
        public string Cilindraje { get; set; }
        public string UnidadSatelital { get; set; }
        public string Modelo { get; set; }
        public string Linea { get; set; }
        public double Km { get; set; }
        public double Peso { get; set; }
        public Nullable<decimal> CLP { get; set; }
        public Nullable<decimal> CantidadDeRecorridos { get; set; }
        public bool Ocupado { get; set; }
        public string NumeroDeVehiculo { get; set; }
        public string CodigoDeZona { get; set; }
        public Nullable<System.DateTime> FechaDeTurno { get; set; }
        public Nullable<bool> EnSeguimientoActualmente { get; set; }
        public string UbicacionActualGPS { get; set; }
        public string VelocidadYSentido { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<bool> EsPropio { get; set; }
        public Nullable<bool> Actividad { get; set; }
        public byte[] Foto { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> UnidadActiva { get; set; }
        public string NumeroDeSerieSatelital { get; set; }
        public string Novedad { get; set; }
        public string OrigenNovedad { get; set; }
    
        public virtual BaseDeCliente BaseDeCliente { get; set; }
        public virtual ICollection<ElManifiestoDeCarga> ElManifiestoDeCargas { get; set; }
        public virtual LaMarca LaMarca { get; set; }
        public virtual LaUbicacionDelCliente LaUbicacionDelCliente { get; set; }
        public virtual LosTiposDeTransmision LosTiposDeTransmision { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes { get; set; }
        public virtual ICollection<LaRotacionRemolque> LaRotacionRemolques { get; set; }
        public virtual LosMotore LosMotore { get; set; }
        public virtual ElTipoDeVehiculo ElTipoDeVehiculo { get; set; }
        public virtual LasZonasDeRuta LasZonasDeRuta { get; set; }
    }
}
