//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDeRemolque
    {
        public BaseDeRemolque()
        {
            this.ElManifiestoDeCargas = new HashSet<ElManifiestoDeCarga>();
            this.ProgramacionParaSeguimientoes = new HashSet<ProgramacionParaSeguimiento>();
            this.LaRotacionRemolques = new HashSet<LaRotacionRemolque>();
            this.LaRotacionRemolques1 = new HashSet<LaRotacionRemolque>();
        }
    
        public string CodigoDeRemolque { get; set; }
        public string CodigoTipoDeVehiculo { get; set; }
        public string NitEmpresa { get; set; }
        public string Placa { get; set; }
        public string CodigoDeEjes { get; set; }
        public string CodigoDeSuspension { get; set; }
        public string CodigoUbicacion { get; set; }
        public double Alto { get; set; }
        public double Ancho { get; set; }
        public double Largo { get; set; }
        public double Espaciamiento { get; set; }
        public double PesoEnVacio { get; set; }
        public decimal CantidadDeEjes { get; set; }
        public double CapacidadPeso { get; set; }
        public double CapacidadVolumen { get; set; }
        public Nullable<System.DateTime> FechaDeRegistro { get; set; }
        public System.DateTime FechaAdquisision { get; set; }
        public bool Nuevo { get; set; }
        public bool Actividad { get; set; }
        public bool Ocupado { get; set; }
        public byte[] Foto { get; set; }
        public string CodigoCliente { get; set; }
    
        public virtual BaseDeCliente BaseDeCliente { get; set; }
        public virtual ElTipoDeVehiculo ElTipoDeVehiculo { get; set; }
        public virtual LaUbicacionDelCliente LaUbicacionDelCliente { get; set; }
        public virtual ICollection<ElManifiestoDeCarga> ElManifiestoDeCargas { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes { get; set; }
        public virtual ICollection<LaRotacionRemolque> LaRotacionRemolques { get; set; }
        public virtual ICollection<LaRotacionRemolque> LaRotacionRemolques1 { get; set; }
        public virtual LosTiposDeEje LosTiposDeEje { get; set; }
        public virtual LosTiposDeSuspension LosTiposDeSuspension { get; set; }
    }
}
