//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenDeCargueTemporal
    {
        public string CodigoDeProducto { get; set; }
        public string Producto { get; set; }
        public string TipoDeRiesgo { get; set; }
        public string NitCliente { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<double> PesoNeto { get; set; }
        public string CodigoDeEmpaque { get; set; }
        public string Destinatario { get; set; }
        public string CodigoDeNaturaleza { get; set; }
        public string UnidadDeMedida { get; set; }
        public string DireccionDestino { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
    
        public virtual ElEmpaque ElEmpaque { get; set; }
        public virtual LaNaturalezaDeLaMercancia LaNaturalezaDeLaMercancia { get; set; }
        public virtual ProductoCliente ProductoCliente { get; set; }
        public virtual LaUnidadDeMedidaCarga LaUnidadDeMedidaCarga { get; set; }
    }
}
