//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElDestino
    {
        public ElDestino()
        {
            this.LasRutasNuevas = new HashSet<LasRutasNueva>();
        }
    
        public string CodigoDeDestino { get; set; }
        public string Destino { get; set; }
    
        public virtual ICollection<LasRutasNueva> LasRutasNuevas { get; set; }
    }
}
