//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElFactorDeCarga
    {
        public string CodigoTipoDeMotor { get; set; }
        public string CodigoCategoriaDePeso { get; set; }
        public double FactorDeCarga { get; set; }
    
        public virtual LosMotore LosMotore { get; set; }
    }
}
