//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTipoDeVehiculo
    {
        public ElTipoDeVehiculo()
        {
            this.BaseDeRemolques = new HashSet<BaseDeRemolque>();
            this.BaseDeVehiculos = new HashSet<BaseDeVehiculo>();
            this.LaSolicitudParaSeguimientoes = new HashSet<LaSolicitudParaSeguimiento>();
            this.LosVehiculosTercerizados = new HashSet<LosVehiculosTercerizado>();
        }
    
        public string CodigoTipoDeVehiculo { get; set; }
        public string TipoDeVehiculo { get; set; }
        public Nullable<double> PesoMInimo { get; set; }
        public Nullable<double> PesoMaximo { get; set; }
        public Nullable<double> PesoDeVehiculo { get; set; }
        public Nullable<bool> SensorCabina { get; set; }
    
        public virtual ICollection<BaseDeRemolque> BaseDeRemolques { get; set; }
        public virtual ICollection<BaseDeVehiculo> BaseDeVehiculos { get; set; }
        public virtual ICollection<LaSolicitudParaSeguimiento> LaSolicitudParaSeguimientoes { get; set; }
        public virtual ICollection<LosVehiculosTercerizado> LosVehiculosTercerizados { get; set; }
    }
}
