//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaCategoriaPorPeso
    {
        public string CodigoCategoriaPeso { get; set; }
        public double PesoMinimo { get; set; }
        public double PesoMaximo { get; set; }
        public string Categoria { get; set; }
    }
}
