//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaRemesaTerrestreDeCarga
    {
        public string CodigoDeRemesa { get; set; }
        public string CodigoDeSolicitud { get; set; }
        public string CodigoOrdenDeCargue { get; set; }
        public string CodigoDeProgramacion { get; set; }
        public string CodigoDeManifiesto { get; set; }
        public Nullable<double> NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaDeCierre { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<double> TotalRemesa { get; set; }
    
        public virtual ElManifiestoDeCarga ElManifiestoDeCarga { get; set; }
        public virtual LaSolicitudParaSeguimiento LaSolicitudParaSeguimiento { get; set; }
    }
}
