//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LasAseguradora
    {
        public string CodigoAseguradora { get; set; }
        public string NitAseguradora { get; set; }
        public string NombreAseguradora { get; set; }
        public string CodigoUbicacion { get; set; }
    
        public virtual LaUbicacionDelCliente LaUbicacionDelCliente { get; set; }
    }
}
