//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaSolicitudParaSeguimiento
    {
        public LaSolicitudParaSeguimiento()
        {
            this.LaRemesaTerrestreDeCargas = new HashSet<LaRemesaTerrestreDeCarga>();
            this.ProgramacionParaSeguimientoes = new HashSet<ProgramacionParaSeguimiento>();
        }
    
        public string CodigoDeSolicitud { get; set; }
        public string CodigoDeCliente { get; set; }
        public string NitEmpresa { get; set; }
        public int CantidadDeDestinatarios { get; set; }
        public string CodigoDeRuta { get; set; }
        public double PesoDeCarga { get; set; }
        public System.DateTime FechaDeReporte { get; set; }
        public System.DateTime FechaDeRequerimiento { get; set; }
        public System.TimeSpan HoraDeRequerimiento { get; set; }
        public string Contacto { get; set; }
        public string CodigoZona { get; set; }
        public string Usuario { get; set; }
        public string CodigoDeEstado { get; set; }
        public bool Activo { get; set; }
        public string CodigoTipoVehiculo { get; set; }
        public string CodigoZonaDestino { get; set; }
        public Nullable<bool> SiEsPropio { get; set; }
        public Nullable<bool> SiEsTercero { get; set; }
        public Nullable<decimal> TelefonoDeContacto { get; set; }
        public Nullable<decimal> CodigoOtroSistema { get; set; }
        public Nullable<bool> PorElDespacho { get; set; }
        public Nullable<bool> PorElControlador { get; set; }
        public Nullable<bool> PorAnulacion { get; set; }
        public string NitEmpresaDestino { get; set; }
        public string CodigoClienteDestino { get; set; }
    
        public virtual BaseDeCliente BaseDeCliente { get; set; }
        public virtual ElTipoDeVehiculo ElTipoDeVehiculo { get; set; }
        public virtual ICollection<LaRemesaTerrestreDeCarga> LaRemesaTerrestreDeCargas { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes { get; set; }
        public virtual LosEstadosDeSolicitudSeguimiento LosEstadosDeSolicitudSeguimiento { get; set; }
        public virtual LasRutasParaSeguimiento LasRutasParaSeguimiento { get; set; }
    }
}
