//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LasRutasNueva
    {
        public string CodigoDeRuta { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string DetalleRecorrido { get; set; }
        public double KilometroDeRuta { get; set; }
        public double TanqueoCargaMaxima { get; set; }
        public double TanqueoCargaMinima { get; set; }
        public decimal TiempoEnRuta { get; set; }
        public double VelocidadPromedio { get; set; }
        public double Corte { get; set; }
        public double Pendiente { get; set; }
        public Nullable<decimal> CostoTotalPeajes { get; set; }
    
        public virtual DetalleDeRuta DetalleDeRuta { get; set; }
        public virtual ElDestino ElDestino { get; set; }
        public virtual ElOrigen ElOrigen { get; set; }
    }
}
