//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LasZonasDeRuta
    {
        public LasZonasDeRuta()
        {
            this.BaseDeVehiculos = new HashSet<BaseDeVehiculo>();
            this.LasRutasParaSeguimientoes = new HashSet<LasRutasParaSeguimiento>();
            this.LasRutasParaSeguimientoes1 = new HashSet<LasRutasParaSeguimiento>();
            this.ProgramacionParaSeguimientoes = new HashSet<ProgramacionParaSeguimiento>();
            this.ProgramacionParaSeguimientoes1 = new HashSet<ProgramacionParaSeguimiento>();
            this.LosVehiculosTercerizados = new HashSet<LosVehiculosTercerizado>();
        }
    
        public string CodigoZona { get; set; }
        public string Zona { get; set; }
    
        public virtual ICollection<BaseDeVehiculo> BaseDeVehiculos { get; set; }
        public virtual ICollection<LasRutasParaSeguimiento> LasRutasParaSeguimientoes { get; set; }
        public virtual ICollection<LasRutasParaSeguimiento> LasRutasParaSeguimientoes1 { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes1 { get; set; }
        public virtual ICollection<LosVehiculosTercerizado> LosVehiculosTercerizados { get; set; }
    }
}
