//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaUbicacionDelCliente
    {
        public LaUbicacionDelCliente()
        {
            this.BaseDeClientes = new HashSet<BaseDeCliente>();
            this.BaseDeRemolques = new HashSet<BaseDeRemolque>();
            this.BaseDeVehiculos = new HashSet<BaseDeVehiculo>();
            this.LasAseguradoras = new HashSet<LasAseguradora>();
        }
    
        public string CodigoDeUbicacion { get; set; }
        public string Ubicacion { get; set; }
        public string Pais { get; set; }
        public Nullable<int> CodigoDeArea { get; set; }
    
        public virtual ICollection<BaseDeCliente> BaseDeClientes { get; set; }
        public virtual ICollection<BaseDeRemolque> BaseDeRemolques { get; set; }
        public virtual ICollection<BaseDeVehiculo> BaseDeVehiculos { get; set; }
        public virtual ICollection<LasAseguradora> LasAseguradoras { get; set; }
    }
}
