//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LosConductoresTercerizado
    {
        public LosConductoresTercerizado()
        {
            this.ElManifiestoDeCargas = new HashSet<ElManifiestoDeCarga>();
            this.ProgramacionParaSeguimientoes = new HashSet<ProgramacionParaSeguimiento>();
        }
    
        public string CodigoConductorTercerizado { get; set; }
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<decimal> Telefono1 { get; set; }
        public Nullable<decimal> Telefono2 { get; set; }
        public Nullable<bool> EnRuta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Licencia { get; set; }
        public Nullable<System.DateTime> FechaExpedicion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Categoria { get; set; }
        public string CodigoUbicacionConductor { get; set; }
        public string CodigoUbicacionLicencia { get; set; }
    
        public virtual ICollection<ElManifiestoDeCarga> ElManifiestoDeCargas { get; set; }
        public virtual ICollection<ProgramacionParaSeguimiento> ProgramacionParaSeguimientoes { get; set; }
    }
}
