//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LosEstadosDeSolicitudSeguimiento
    {
        public LosEstadosDeSolicitudSeguimiento()
        {
            this.LaSolicitudParaSeguimientoes = new HashSet<LaSolicitudParaSeguimiento>();
        }
    
        public string CodigoDeEstado { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<LaSolicitudParaSeguimiento> LaSolicitudParaSeguimientoes { get; set; }
    }
}
