//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LosMotore
    {
        public LosMotore()
        {
            this.BaseDeVehiculos = new HashSet<BaseDeVehiculo>();
            this.ElFactorDeCargas = new HashSet<ElFactorDeCarga>();
            this.LosVehiculosTercerizados = new HashSet<LosVehiculosTercerizado>();
        }
    
        public string CodigoTipoDeMotor { get; set; }
        public string Nombre { get; set; }
        public double Factor { get; set; }
    
        public virtual ICollection<BaseDeVehiculo> BaseDeVehiculos { get; set; }
        public virtual ICollection<ElFactorDeCarga> ElFactorDeCargas { get; set; }
        public virtual ICollection<LosVehiculosTercerizado> LosVehiculosTercerizados { get; set; }
    }
}
