//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LosTiposDeSuspension
    {
        public LosTiposDeSuspension()
        {
            this.BaseDeRemolques = new HashSet<BaseDeRemolque>();
        }
    
        public string CodigoSuspension { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<BaseDeRemolque> BaseDeRemolques { get; set; }
    }
}
