//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoCliente
    {
        public string CodigoDeProducto { get; set; }
        public string Producto { get; set; }
        public string TipoDeRiesgo { get; set; }
        public string CodigoMin { get; set; }
        public string ProductoMin { get; set; }
    
        public virtual DetalleOrdenDeCargueTemporal DetalleOrdenDeCargueTemporal { get; set; }
    }
}
