//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionParaSeguimiento
    {
        public string CodigoDeProgramacion { get; set; }
        public string CodigoDeSeguridad { get; set; }
        public System.DateTime FechaDeProgramación { get; set; }
        public bool EsPropio { get; set; }
        public bool EsTercero { get; set; }
        public string CodigoConductorPropio { get; set; }
        public string CodigoConductorTercerizado { get; set; }
        public string CodigoDeVehiculoPropio { get; set; }
        public string CodigoDeRemolque { get; set; }
        public string CodigoDeVehiculoTercero { get; set; }
        public string CodigoDeSolicitud { get; set; }
        public string CodigoZona { get; set; }
        public string UsuarioDeSeguimiento { get; set; }
        public string UsuarioDeDespachos { get; set; }
        public Nullable<bool> Despachado { get; set; }
        public Nullable<bool> Consignacion { get; set; }
        public string Banco { get; set; }
        public Nullable<bool> EnviarDocumentacion { get; set; }
        public Nullable<double> Anticipo { get; set; }
        public string Observaciones { get; set; }
        public string CodigoZonaDeDestino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaDespachos { get; set; }
        public string Documentacion { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<System.DateTime> HoraDeLLegadaProgramada { get; set; }
        public string LugarDeCargue { get; set; }
        public string RemolqueTercero { get; set; }
        public string ManifiestoDeCarga { get; set; }
        public string CodigoDeManifiesto { get; set; }
    
        public virtual BaseDeRemolque BaseDeRemolque { get; set; }
        public virtual BaseDeVehiculo BaseDeVehiculo { get; set; }
        public virtual LaSolicitudParaSeguimiento LaSolicitudParaSeguimiento { get; set; }
        public virtual LasZonasDeRuta LasZonasDeRuta { get; set; }
        public virtual LasZonasDeRuta LasZonasDeRuta1 { get; set; }
        public virtual LosConductore LosConductore { get; set; }
        public virtual LosConductoresTercerizado LosConductoresTercerizado { get; set; }
        public virtual LosVehiculosTercerizado LosVehiculosTercerizado { get; set; }
    }
}
