//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rndc.ServiceReferenceRNDC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRNDC.IBPMServices")]
    public interface IBPMServices {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:BPMServicesIntf-IBPMServices) del mensaje AtenderMensajeRNDCRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeRNDC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCResponse AtenderMensajeRNDC(Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:BPMServicesIntf-IBPMServices) del mensaje AtenderMensajeBPMRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeBPM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Rndc.ServiceReferenceRNDC.AtenderMensajeBPMResponse AtenderMensajeBPM(Rndc.ServiceReferenceRNDC.AtenderMensajeBPMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeRNDC", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeRNDCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Request;
        
        public AtenderMensajeRNDCRequest() {
        }
        
        public AtenderMensajeRNDCRequest(string Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeRNDCResponse", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeRNDCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AtenderMensajeRNDCResponse() {
        }
        
        public AtenderMensajeRNDCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeBPM", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeBPMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Request;
        
        public AtenderMensajeBPMRequest() {
        }
        
        public AtenderMensajeBPMRequest(string Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeBPMResponse", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeBPMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AtenderMensajeBPMResponse() {
        }
        
        public AtenderMensajeBPMResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBPMServicesChannel : Rndc.ServiceReferenceRNDC.IBPMServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BPMServicesClient : System.ServiceModel.ClientBase<Rndc.ServiceReferenceRNDC.IBPMServices>, Rndc.ServiceReferenceRNDC.IBPMServices {
        
        public BPMServicesClient() {
        }
        
        public BPMServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BPMServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCResponse Rndc.ServiceReferenceRNDC.IBPMServices.AtenderMensajeRNDC(Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCRequest request) {
            return base.Channel.AtenderMensajeRNDC(request);
        }
        
        public string AtenderMensajeRNDC(string Request) {
            Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCRequest inValue = new Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCRequest();
            inValue.Request = Request;
            Rndc.ServiceReferenceRNDC.AtenderMensajeRNDCResponse retVal = ((Rndc.ServiceReferenceRNDC.IBPMServices)(this)).AtenderMensajeRNDC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rndc.ServiceReferenceRNDC.AtenderMensajeBPMResponse Rndc.ServiceReferenceRNDC.IBPMServices.AtenderMensajeBPM(Rndc.ServiceReferenceRNDC.AtenderMensajeBPMRequest request) {
            return base.Channel.AtenderMensajeBPM(request);
        }
        
        public string AtenderMensajeBPM(string Request) {
            Rndc.ServiceReferenceRNDC.AtenderMensajeBPMRequest inValue = new Rndc.ServiceReferenceRNDC.AtenderMensajeBPMRequest();
            inValue.Request = Request;
            Rndc.ServiceReferenceRNDC.AtenderMensajeBPMResponse retVal = ((Rndc.ServiceReferenceRNDC.IBPMServices)(this)).AtenderMensajeBPM(inValue);
            return retVal.@return;
        }
    }
}
